version: '3'
services:
  frontend:
    build:
      context: ./visitor-client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    

  backend:
    build:
      context: ./visits-starter
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - redis
    

  redis:
    image: redis
    ports:
      - 6379:6379
